language: node_js
node_js:
- "0.10"
before_install: 
- npm install -g grunt-cli
- sudo add-apt-repository -y ppa:moti-p/cc
- sudo apt-get update
- sudo apt-get -y --reinstall install imagemagick
- printf "\n" | pecl install apcu-beta
- printf "\n" | pecl install imagick-beta
install: npm install